#!/usr/bin/env bash
# ============================================================================
# bootstrap.sh - prepare a fresh Ubuntu 24.04 host to run this playbook
# locally against itself. Run as root from the provider console:
#
#     ./bootstrap.sh          # install deps + set up local inventory
#     ./bootstrap.sh --run    # ...then run site.yml immediately
#
# Idempotent: safe to re-run.
# ============================================================================
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOCAL_INV="${HERE}/inventory/local.ini"
RED=$'\033[31m'; GRN=$'\033[32m'; YEL=$'\033[33m'; RST=$'\033[0m'

info() { printf '%s==>%s %s\n' "$GRN" "$RST" "$*"; }
warn() { printf '%s[!]%s %s\n' "$YEL" "$RST" "$*"; }
die()  { printf '%s[x]%s %s\n' "$RED" "$RST" "$*" >&2; exit 1; }

# --- Preconditions ---------------------------------------------------------
[[ ${EUID} -eq 0 ]] || die "Run as root (use 'sudo ./bootstrap.sh' or the console root shell)."

. /etc/os-release
[[ "${ID:-}" == "ubuntu" && "${VERSION_ID:-}" == "24.04" ]] \
  || die "This targets Ubuntu 24.04 LTS (found: ${ID:-?} ${VERSION_ID:-?})."

# --- Install Ansible + git -------------------------------------------------
if command -v ansible-playbook >/dev/null 2>&1 && command -v git >/dev/null 2>&1; then
  info "ansible + git already present - skipping apt install."
else
  info "Installing ansible + git ..."
  export DEBIAN_FRONTEND=noninteractive
  apt-get update -qq
  apt-get install -y -qq ansible git
fi
info "$(ansible --version | head -1)"

# --- Install required collections ------------------------------------------
info "Installing Ansible collections from requirements.yml ..."
ansible-galaxy collection install -r "${HERE}/requirements.yml"

# --- Generate local inventory (localhost, no SSH) --------------------------
info "Writing local inventory -> ${LOCAL_INV}"
cat > "${LOCAL_INV}" <<'EOF'
# Auto-generated by bootstrap.sh - provision this host against itself.
[k8s_nodes]
localhost ansible_connection=local ansible_python_interpreter=/usr/bin/python3
EOF

# --- Done / optional run ---------------------------------------------------
cat <<EOF

${GRN}Environment ready.${RST}

Next:
  1. (recommended) review configuration:
       \$EDITOR ${HERE}/group_vars/all.yml
  2. provision this host:
       cd ${HERE}
       ansible-playbook -i inventory/local.ini site.yml
  3. validate:
       ./validate.sh

Generated sysadmin password(s) will be written to:
  ${HERE}/.secrets/credentials.yml   (chmod 0600, git-ignored)
EOF

if [[ "${1:-}" == "--run" ]]; then
  info "Running site.yml now (--run) ..."
  cd "${HERE}"
  ansible-playbook -i inventory/local.ini site.yml
  info "Provision complete. Running validation ..."
  ./validate.sh
fi
