---
- name: Validate and reload sshd
  ansible.builtin.command: sshd -t
  changed_when: false
  notify: Restart sshd

- name: Restart sshd
  ansible.builtin.systemd_service:
    name: ssh
    state: restarted
