---
- name: Assert target OS is Ubuntu
  ansible.builtin.assert:
    that:
      - ansible_distribution == "Ubuntu"
    fail_msg: "Unsupported OS: {{ ansible_distribution }} (Ubuntu 24.04 required)"
    quiet: true

- name: Assert Ubuntu 24.04
  ansible.builtin.assert:
    that:
      - ansible_distribution_version == "24.04"
    fail_msg: "Unsupported Ubuntu version: {{ ansible_distribution_version }} (24.04 required)"
    quiet: true

- name: Assert supported CPU architecture
  ansible.builtin.assert:
    that:
      - ansible_architecture in ["x86_64", "aarch64"]
    fail_msg: "Unsupported architecture: {{ ansible_architecture }}"
    quiet: true
